gcloud ml-engine local train \
	--module-name trainer.train_cloud \
	--package-path trainer \
	--job-dir output \
	-- \
	--train-files data/train.json \
        --fc-layers 2 \
	--dropouts 0 \
	--trainable-layers 0 \
	--steps-per-epoch 1 \
	--num-epochs 1
